### ISSUE TITLE
Incorrect leaps version

### ISSUE THREAD

**Issue by Enchufa2** [WLenhard/cNORM#1]
Should be 3.0 instead of 3.0.0. This doesn't matter on CRAN, because in R package_version("3.0") == package_version("3.0.0"), but I found it causes issues in other systems (e.g., RPM packaging).

**Comment by WLenhard** [comment]
Thank you very much. I wasn't aware of that. The issue is fixed in the code and it will be incorporated in the next official release to CRAN.
