### ISSUE TITLE
object ‘askYesNo’ is not exported by 'namespace:utils'

### ISSUE THREAD

**Issue by SteHab** [WLenhard/cNORM#2]
OS: Linux Mint 19.2; R version 3.4.4

_** preparing package for lazy loading
Error : object ‘askYesNo’ is not exported by 'namespace:utils'
ERROR: lazy loading failed for package ‘cNORM’
Warning in install.packages :
  installation of package ‘cNORM’ had non-zero exit status_

leap, RColorBrewer and latticeExtra are installed.

**Comment by WLenhard** [comment]
Thanks for the hint. I think, it has to do with your R version. The askYesNo function entered the R utils package in R v3.5.0. Frankly, it is just a fancy user interaction and not central to cNORM. I will think about removing it. If this is possible for you, could you check if the error still occurs with a current installation of R?

Thanks and with best regards, Wolfgang

**Comment by WLenhard** [comment]
askYesNo wasn't even needed. I removed it from the namespace. The source was updated in GitHub, but of course, the current version on CRAN still incorporates it.
