### ISSUE TITLE
argument is of length zero

### ISSUE THREAD

**Issue by siwanicki** [WLenhard/cNORM#3]
I am trying to use the shiny app for cNORM but when I open my dataset, I cannot get past preparation as I get the error: Error:argument is of length zero

**Comment by WLenhard** [comment]
Could you provide a sample dataset to reproduce the error? It might be an issue with the data format of your variables. Both must be numeric in nature. In case, cols include text, they are mapped to factors at the data import. This most likely causes the problem. I will add additional checks on this in the package.
