### ISSUE TITLE
Bug in pretty formatting for rawTable()

### ISSUE THREAD

**Issue by DSHerzberg** [WLenhard/cNORM#5]
In the attached screen shot, you can see that "pretty = TRUE" returned three rows for the 1-74 range of raw scores, whereas it should have returned only a single row for the 1-74 range.

<img width="205" alt="Screen Shot 2021-10-18 at 3 48 36 PM" src="https://user-images.githubusercontent.com/46504617/137816916-b797108d-2b77-48dc-b001-17455fc95a90.png">

**Comment by WLenhard** [comment]
Sorry, forgot to close this one. Prettyprint functionality has been corrected some month before and it hopefully works now as desired. Thanks for pointing this out!
