### ISSUE TITLE
Error when selecting specific predictors

### ISSUE THREAD

**Issue by jirimotyl** [WLenhard/cNORM#8]
When using the function bestModel, the predictors I specified started causing error of this type:

Error in (!is.null(predictors)) && (!inherits(predictors, "formula")) &&  : 
  'length = 5' in coercion to 'logical(1)'

This happens also in scripts that were fully functioning between 1 and 2 years ago. I am not sure whether I miss something or whether there is some more general error causing this issue?  

This is example of my code leading to this issue:
norms_bvmt_model <- bestModel(norms_powers, raw = "score_total", predictors = c("L1", "L3", "L1A3", "A2", "A3"), plot = T, terms = 3)

**Comment by WLenhard** [comment]
Dear @jirimotyl 
many thanks for reporting the error. I could already locate and fix it. It is related to a change in how strict R handels comparison of vectors with logical operators and there was a change somewhere in R4.0 or 4.1. I will run tests and prepare a release in the course of the day. The version number will be 3.1.0.

Best regards!
Wolfgang

**Comment by WLenhard** [comment]
The new package (3.1.0) is on its way to CRAN and should be available in a few hours via install.packages.
